### ISSUE TITLE
How do we have to declare Adunit & Line item configuration on GAM for this example? 

### ISSUE THREAD

**Issue by badalaque** [googleads/hbbtv-lshape-demo#1]
Hi,

I'm trying to test this example using our Google Ad Manager account, but we have some dudes about how to declare the adunit on inventory in order to work properly.

¿What sizes do we have to use for this adunit?

Thanks for your help.

![image](https://user-images.githubusercontent.com/15980990/217889174-76b056e8-f5ab-4759-ad94-304fbd67c7e9.png)

**Comment by Christophe-google** [comment]
The creative used in this sample code is booked as a custom creative (see https://support.google.com/admanager/answer/3180782) and uses the size 1x1
